version: "3.9"

x-logging:
  &default-logging
  options:
    max-size: "50m"
    max-file: "3"
  driver: json-file

services:
  prometheus:
    build: prometheus
    user: 0:0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./data/prometheus:/prometheus
    logging: *default-logging

  grafana:
    build:
      context: grafana
      args:
        - GF_SERVER_ROOT_URL=grafana.audius.co
    user: 0:0
    env_file:
      - grafana/.env
    links:
      - prometheus:prometheus
    ports:
      - "80:3000"
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana
    logging: *default-logging

  # Exporters

  exporter_alchemy:
    build: exporters/alchemy
    volumes:
      - ./exporters/alchemy/main.js:/app/main.js
    ports:
      - "2000:3000"
    environment:
      - ALCHEMY_WEBSOCKETS
    logging: *default-logging

  exporter_sdk:
    build: exporters/sdk
    volumes:
      - ./exporters/sdk/main.js:/app/main.js
    ports:
      - "2001:3000"
    logging: *default-logging

  ## Elasticsearch Exporter

  exporter_elasticsearch_dn1:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.3.0
    ports:
      - "9114:9114"
    command:
      - '--es.uri=http://dn1_elasticsearch_1:9200'
    restart: always
    networks:
      - audius_dev
    logging: *default-logging

  ## Postgres Exporters

  exporter_postgres_dn1:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "5010:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@dn1_discovery-provider-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - audius_dev
    logging: *default-logging

  exporter_postgres_cn1:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "4010:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@cn1_creator-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - audius_dev
    logging: *default-logging

  exporter_postgres_cn2:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "4011:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@cn2_creator-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - audius_dev
    logging: *default-logging

  exporter_postgres_cn3:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "4012:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@cn3_creator-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - audius_dev
    logging: *default-logging

  exporter_postgres_cn4:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "4013:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@cn4_creator-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - audius_dev
    logging: *default-logging

  exporter_postgres_is:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "7010:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@audius-identity-service_identity-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - audius_dev
    logging: *default-logging

networks:
  audius_dev:
    external: true
