global:
  scrape_interval:     30s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

scrape_configs:

  # monitor itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'exporters-alchemy'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:2000']
        labels:
          host: 'host.docker.internal'
          environment: 'prod'
          service: 'exporter'
          target: 'alchemy'

  - job_name: 'exporters-sdk'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:2001']
        labels:
          host: 'host.docker.internal'
          environment: 'prod'
          service: 'exporter'
          target: 'audius-sdk'
